version: "3.7"

services:
  iceheadbot_postgresql:
    container_name: "iceheadbot_postgresql"
    ports:
      - '5432:5432'
    image: postgres:16rc1-alpine3.18
    environment:
      POSTGRES_DB: "bot-db"
      POSTGRES_USER: "bot-user"
      POSTGRES_PASSWORD: "bot-password"
